---
- name: Set up debian box
  hosts: all
 # Settings from https://tailscale.com/docs/features/exit-nodes?tab=linux
  pre_tasks:
    - name: Enable IP forwarding for Tailscale exit node
      when: "'tailscale' in group_names"
      become: true
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_file: /etc/sysctl.d/99-tailscale.conf
        sysctl_set: true
        state: present
        reload: true
      loop:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
      tags: tailscale
  roles:
    - system
    - role: disks
      when: "'vm' not in group_names and 'pi' not in group_names"
    - editor
    #   - mounts
    - backups
    #   - containers
    - terminal
    - role: artis3n.tailscale.machine
      when: "'tailscale' in group_names"
      vars:
        tailscale_args: "--advertise-exit-node --advertise-routes=192.168.1.0/24"
      tags: tailscale
    - notifications
    - file_manager
    #   - reverse_proxy
    - drift_management
    - hifis.toolkit.unattended_upgrades
